### ISSUE TITLE
Orion UI makes requests only to 127.0.0.1:4200 and ignores PREFECT_API_URL

### ISSUE THREAD

**Issue by devdua** [PrefectHQ/prefect#5648]
## Description

I’m using Prefect 2.0b and I am running it on my dev machine.. I want to access the Orion UI from another machine but it shows me no data because the web app is making API calls to `127.0.0.1:4200` instead of the API URL I set (using `PREFECT_API_URL`) to `0.0.0.0:4200/api`, which fails because the API is listening on the dev machine and not locally on the machine I am accessing Orion from.

I have to self-host and can't use Prefect Cloud (as was suggested to me in your Slack channel)

## Reproduction / Example

```
$ prefect --version
2.0b2

$ prefect orion start
Starting...

 ___ ___ ___ ___ ___ ___ _____    ___  ___ ___ ___  _  _
| _ \ _ \ __| __| __/ __|_   _|  / _ \| _ \_ _/ _ \| \| |
|  _/   / _|| _|| _| (__  | |   | (_) |   /| | (_) | .` |
|_| |_|_\___|_| |___\___| |_|    \___/|_|_\___\___/|_|\_|

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://0.0.0.0:4200/api

Check out the dashboard at http://0.0.0.0:4200
```
![image](https://user-images.githubusercontent.com/3139249/161959074-4f8e9032-8758-4ae8-a6d0-dfe916aae71f.png)

**Comment by madkinsz** [comment]
Hi! The UI is currently hardcoded to make requests to localhost but we are working on a way for it to respect the API url .

**Comment by jory3** [comment]
I tried fixing this by replacing this 3 occurences of the hard coded url by the ENV variable, but it didn't work: 
orion-ui/packages/orion-design/src/services/Api.ts:12
orion-ui/src/plugins/api.ts:237
orion-ui/src/utilities/api.ts:5

I tried:
``process.env.PREFECT_API_URL``
I'm not a node developer, so probably this was a very naive try

**Comment by madkinsz** [comment]
Yeah the issue is that the UI is a static application after being built so the env variable is a constant at build time. We've got a fix on the way.

**Comment by KiburmSong** [comment]
I have got similar problem. I use also Prefect Server and other client. 
In the client, I can run the prefect flow. But I cannot see any data in the host UI. 

I changes config set PREFECT_ORION_HOST=0.0.0.0 and PREFECT_ORION_PORT=7000

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/10234305/163595573-1d000ab9-ef7c-499d-9741-b8c3ec029fdf.png">

And I cannot see any settings after I changed config

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/10234305/163595653-dcf72e02-c052-464a-a332-11259bc1c220.png">

I found that the config was not changed completely. PREFECT_ORION_API_HOST and PREFECT_ORION_API_PORT are duplicated. 

PREFECT_PROFILE='test'
PREFECT_ORION_API_HOST='0.0.0.0'
PREFECT_ORION_API_PORT='7000'
PREFECT_AGENT_PREFETCH_SECONDS='10'
PREFECT_AGENT_QUERY_INTERVAL='5.0'
...
PREFECT_ORION_API_DEFAULT_LIMIT='200'
PREFECT_ORION_API_HOST='127.0.0.1'
PREFECT_ORION_API_PORT='4200'
...

Finally, I hardcoded host and port in the /prefect/setting.py 
I converted the default '127.0.0.1' to '0.0.0.0' and '4200' to '7000'
But it doesn't work. I did my best and failed.

**Comment by max13fr** [comment]
Same here, changing host not update xhr calls urls

**Comment by madkinsz** [comment]
This _will not work yet_. There is not an easy workaround. I will update this issue when we have added this functionality.

**Comment by simonm3** [comment]
I have two docker containers for orion server and prefect client. This is working:

* client image includes ENV PREFECT_API_URL=http://host.docker.internal:4200/api
* server image includes CMD ["prefect", "orion", "start", "--host", "0.0.0.0"]

**Comment by wfclark5** [comment]
@zangell44 was this issue closed because it was fixed and will be in the next release?

**Comment by madkinsz** [comment]
This fix will be in the next release.

**Comment by wfclark5** [comment]
> This fix will be in the next release.

Hurray! Thank you @madkinsz

**Comment by anna-geller** [comment]
> Hi! It seems the new release (b4) doesn't fix the issue Here the URL is still hardcoded:
> 
> https://github.com/PrefectHQ/prefect/blob/cb8aa4f255f4c8207979d5d970da461674451956/orion-ui/src/plugins/api.ts#L237
> 
> Should we wait for another fix? thanks :)

@Vict0r7 we've pushed a fix internally and we'll release it later this week - thanks for reporting this!

**Comment by A-baoYang** [comment]
Hi, I've tried the new release (2.0b5), and here's my settings:
```
PREFECT_ORION_API_HOST='0.0.0.0'
PREFECT_ORION_API_PORT='4242'
```
Inside the docker container, I run `prefect orion start` to launch the dashboard, 
and I connect the dashboard outside the container at `127.0.0.1:4242`
with the `docker run -p 4242:4242 ...` command.

The dashboard can successfully on, but the run_history plot doesn't show:
![image](https://user-images.githubusercontent.com/9716977/172212600-f0e200b8-12c6-449c-8a78-644fe6a17008.png)

---
But if I host the dashboard at `127.0.0.1:4201`, which is:
```
PREFECT_ORION_API_HOST='127.0.0.1'
PREFECT_ORION_API_PORT='4201'
```
The run_history plot can successfully show:
![image](https://user-images.githubusercontent.com/9716977/172213035-84807409-5f0a-46f6-986d-3565ab747eef.png)

I have the same environment both inside docker container and outside:
- python: 3.7.9
- prefect: 2.0b5

Will the next release fix the issue?

**Comment by anna-geller** [comment]
> Hi, I've tried the new release (2.0b5), and here's my settings:
> 
> ```
> PREFECT_ORION_API_HOST='0.0.0.0'
> PREFECT_ORION_API_PORT='4242'
> ```
> 
> Inside the docker container, I run `prefect orion start` to launch the dashboard, and I connect the dashboard outside the container at `127.0.0.1:4242` with the `docker run -p 4242:4242 ...` command.
> 
> The dashboard can successfully on, but the run_history plot doesn't show: ![image](https://user-images.githubusercontent.com/9716977/172212600-f0e200b8-12c6-449c-8a78-644fe6a17008.png)
> 
> But if I host the dashboard at `127.0.0.1:4201`, which is:
> 
> ```
> PREFECT_ORION_API_HOST='127.0.0.1'
> PREFECT_ORION_API_PORT='4201'
> ```
> 
> The run_history plot can successfully show: ![image](https://user-images.githubusercontent.com/9716977/172213035-84807409-5f0a-46f6-986d-3565ab747eef.png)
> 
> I have the same environment both inside docker container and outside:
> 
> * python: 3.7.9
> * prefect: 2.0b5
> 
> Will the next release fix the issue?

try adding this from the machine you want to access the UI:

```
prefect config set PREFECT_ORION_UI_API_URL="http://<external-ip>:4200/api"
```

**Comment by anna-geller** [comment]
@A-baoYang, we've released Prefect 2.0b6 yesterday - can you try upgrading to that version and try again?

**Comment by A-baoYang** [comment]
@anna-geller 
Thank you so much.
After testing, `2.0b6` works!

![](https://i.imgur.com/QBKthfr.png)

- python: 3.7.9
- prefect: 2.0b6
- docker: 20.10.7

**Comment by chuanhao01** [comment]
Not sure if its the intended behavior or if this is the right place.

If anyone else is running prefect (Orion UI/Prefect server in 1 container) and want to be able to access the webpage outside of the container, you need to set the `PREFECT_ORION_API_HOST="127.0.0.1"` and start the server with `prefect orion start --host 0.0.0.0`.

From some testing with the `2.0b6-PythonX` and `sha-502ee00-PythonX` it seems that the webpage uses the `PREFECT_ORION_API_HOST` env var to decide what host to use when sending subsequent requests for data.

So if you are just setting the env var to `0.0.0.0` to allow you to host the server on `0.0.0.0` you will run into the issue where the webpage loads with no data.

Minimal Example:
```yaml
# docker-compose.yml
services:
  prefect-server:
    image: prefecthq/prefect:2.0b6-python3.10
    ports:
      - target: 4200
        published: 4200
    environment:
      PREFECT_ORION_API_HOST: 127.0.0.1
      PREFECT_ORION_API_PORT: 4200
    command: prefect orion start --host 0.0.0.0
```

**Comment by gq1** [comment]
I used Helm chart to install with docker image 2.0b7, still the same problem for me. I put a issues in helm chart repo.

https://github.com/PrefectHQ/prefect-helm/issues/6

**Comment by kwmiebach** [comment]
I was having similar problems when running orion and some flows with
docker on a remote host, even with prefect v 2.0.4.

The orion gui would not show anything, only empty sub-pages.

The gui does xhr requests all the time and uses the evironment settings that it finds to reach the orion server.

This not being set correctly was the reason why the orion gui in the browser showed nothing for me.

The error was visible on the chrome or firefox developer console when 
clicking on the different menu items. Orion decided to ignore the not reachable XHR calls silently. 

I also found it is important to always fully reload the browser gui after any change or container restart. Ctrl-r in the browser does a complete reload.

What solved the whole issue for me was to set some environment variables according to my setup. I ended up with a docker compose file similar to this:


```
version: "3.7"
services:

    orion:
        container_name: orion
        image: prefecthq/prefect:2.0.4-python3.7
        ports:
            - 9999:4200
        environment:
            PREFECT_ORION_API_HOST: 127.0.0.1
            PREFECT_ORION_API_PORT: 4200
            PREFECT_ORION_UI_API_URL: http://host.example.com:9999/api
        command: prefect orion start --host 0.0.0.0 --port 4200

    flow:
        container_name: flow
        depends_on:
        - orion
        environment:
            PREFECT_API_URL: http://prefect:4200/api
        ... 
```

### Some Explanations

I am using a separate container for orion and for the flows. 

To fit multiple setups and for clarity I am using a different port and a hostname on the `outside`,
in this case port 9999 and the hostname of the server, where docker is running is host.example.com
in the example. 

So in the example nothing is running on my client computer except the browser and an ssh client to access the commandline of the server.

Note the orion startup command, we are telling orion to listen
on all interfaces '0.0.0.0' inside its docker container.

This will bind to the container's localhost and also bind to the
containers IP inside the docker network, which is made up and set 
by docker at runtime. 

To be able to access this container IP from the flow container
I am accessing it using the container name 'orion' and docker will
resolve it at runtime also from inside the flow container.

The other important setting is the PREFECT_ORION_UI_API_URL.
In the example the host is host.example.com which is my docker host
and 9999 is the port that orion listens to for the browser gui.

I am not sure if the whole solution could be further simplified, but I am happy to 
have a running setup at last. 

This is a lab example and in a production environment security would still have to be added to the setup.

**Comment by jwlarocque** [comment]
I also ran into this (running 2.4.5 in EKS).  Solution was to set PREFECT_ORION_UI_API_URL as @kwmiebach described, to avoid a value of None defaulting to 127.0.0.1, but this seems extremely unintuitive to me.  

Looking through [the UI code](https://github.com/PrefectHQ/prefect/blob/2.4.5/orion-ui/src/services/uiSettings.ts#L17), maybe this happens because Vite is in development mode?  In any case, this seems more like a workaround than intended behavior.

```
Version:             2.4.5
API version:         0.8.1
Python version:      3.7.14
Git commit:          dbe27317
Built:               Thu, Sep 29, 2022 3:05 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          postgresql
```

**Comment by anna-geller** [comment]
@jwlarocque for Kubernetes OSS deployments, check out the helm repo: https://github.com/PrefectHQ/prefect-helm

**Comment by mikelogaciuk** [comment]
@anna-geller 

> @jwlarocque for Kubernetes OSS deployments, check out the helm repo: https://github.com/PrefectHQ/prefect-helm

The official Helm Chart is broken.

It throws an error about connection to UI (Can't connect to ORION API).

**Comment by anna-geller** [comment]
why do you claim it's broken? Perhaps some configuration missing? I'd encourage you to open a GitHub issue in the helm chart repo detailing which steps you took, which version do you use, and which error do you get and when it happens

you can link to this issue
