### ISSUE TITLE
ValueError: Path does not exist

### ISSUE THREAD

**Issue by mikkelduif** [PrefectHQ/prefect#6779]
### First check

- [x] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I frequently get the error `raise ValueError(f"Path {path} does not exist.")` and I do not have any context on why it happens.

### Reproduction

```python
N/A
```

### Error

```bash
Encountered exception during execution:
Traceback (most recent call last):
  File "./.venv/lib/python3.10/site-packages/prefect/engine.py", line 595, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "./.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "./.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "./.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "./.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "././flows/etl/flow.py", line 81, in myflow
    val = myflow(
  File "./.venv/lib/python3.10/site-packages/prefect/flows.py", line 384, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "./.venv/lib/python3.10/site-packages/prefect/engine.py", line 162, in enter_flow_run_engine_from_flow_call
    return run_async_from_worker_thread(begin_run)
  File "./.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 137, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "./.venv/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "./.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "./.venv/lib/python3.10/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "./.venv/lib/python3.10/site-packages/prefect/engine.py", line 442, in create_and_begin_subflow_run
    flow_run.state.data._cache_data(await _retrieve_result(flow_run.state))
  File "./.venv/lib/python3.10/site-packages/prefect/results.py", line 38, in _retrieve_result
    serialized_result = await _retrieve_serialized_result(state.data)
  File "./.venv/lib/python3.10/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "./.venv/lib/python3.10/site-packages/prefect/results.py", line 34, in _retrieve_serialized_result
    return await filesystem.read_path(result.key)
  File "./.venv/lib/python3.10/site-packages/prefect/filesystems.py", line 183, in read_path
    raise ValueError(f"Path {path} does not exist.")
ValueError: Path /root/.prefect/storage/6543f194d24f4ad89685f79e67227492 does not exist.
```

### Versions

```
Version:             2.3.1
API version:         0.8.0
Python version:      3.10.7
Git commit:          1d485b1d
Built:               Thu, Sep 1, 2022 3:53 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by madkinsz** [comment]
See also https://github.com/PrefectHQ/prefect/issues/6086

If you could provide a MRE that would be very helpful. It's going to be hard for us to solve this issue without a reproducible example.

**Comment by samgarvis** [comment]
The below is the current deployment we are using
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"name":"prefect-agent"}]},"output":{"containers":[{"limits":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"prefect-agent"}]},"modified":true}'
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: prod-prefect-agent-1
    meta.helm.sh/release-namespace: prod-prefect
  creationTimestamp: "2022-08-31T18:42:15Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: prod-prefect-agent-1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prefect-agent
    app.kubernetes.io/version: latest
    helm.sh/chart: prefect-agent-0.3.2
  name: prod-prefect-agent-1
  namespace: prod-prefect
  resourceVersion: "23272922"
  uid: xxxxxxxxxxxxxxxx
spec:
  progressDeadlineSeconds: 600
  replicas: 8
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: prod-prefect-agent-1
      app.kubernetes.io/name: prefect-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: prod-prefect-agent-1
        app.kubernetes.io/name: prefect-agent
    spec:
      affinity: {}
      containers:
      - command:
        - prefect
        - agent
        - start
        - xxxxxxxxxxxxxxxxxxx
        env:
        - name: PREFECT_DEBUG_MODE
          value: "true"
        - name: PREFECT_API_URL
          value: https://api.prefect.cloud/api/accounts/xxxxxxxxxxxx/workspaces/xxxxxxxxxxxx
        - name: PREFECT_API_KEY
          valueFrom:
            secretKeyRef:
              key: prefect-prod-service-key
              name: prefect-prod-service-secret
        image: us-east1-docker.pkg.dev/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxx/prefect20:latest
        imagePullPolicy: Always
        name: prefect-agent
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: prod-prefect-agent-1
      serviceAccountName: prod-prefect-agent-1
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 8
  conditions:
  - lastTransitionTime: "2022-08-31T18:42:15Z"
    lastUpdateTime: "2022-09-06T16:21:43Z"
    message: ReplicaSet "prod-prefect-agent-1-7c496d6bb5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-09-11T05:37:07Z"
    lastUpdateTime: "2022-09-11T05:37:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 8
  replicas: 8
  updatedReplicas: 8
```
Below is an example flow that keeps "crashing".
```
from prefect_gcp import GcpCredentials
from prefect_gcp.bigquery import bigquery_query
import json
import os
import logging
import ast 
import prefect
from prefect import task, flow
import pandas as pd
import slack
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud import storage
import pygsheets
from prefect.blocks.system import Secret


@flow
def xxxxxxxxxxx(gcloud_auth, sleeper=0):
    client = GcpCredentials(
            service_account_info=gcloud_auth,
            project='xxxxxxxxxxxx'
        ).get_bigquery_client()
    query_string = """
        SELECT
            COUNT(*) AS xxxxxxxx
        FROM `xxxxxxxxxxxxxxxx`
        WHERE xxx=xxxx
    """
    query_job = client.query(query_string)
    df = query_job.to_dataframe()
    num_signups = df.colorado_signups.max()
    return num_signups

@task
def xxxxxxxxxxxxxxxxx(xxxxxxx, slack_oauth):
    channel = 'xxxxxxxxxxxx'
    if xxxxxxx < 7000:
        message = f':white_check_mark: {xxxxxxxxx}'
    elif xxxxxxxx < 7500:
        message = f':warning: {xxxxxxxxx} <@xxxxxx>'
    else:
        message = f':rotating_light: {xxxxxxxx} <@xxxxx>'
    client = slack.WebClient(token=slack_oauth)
    client.chat_postMessage(channel="xxxxxxxxxxx", text=message)
    return

@flow(name="xxxxxx")
def xxxxxxxxx():
    gcloud_auth = Secret.load("gcloud-prod-auth").get()
    slack_oauth = Secret.load("slackbot-oauth").get()
    
    xxxxxxx = xxxxxxxxx(gcloud_auth)
    xxxxxxxxxxx(xxxxxxx, slack_oauth, wait_for=[xxxxxxx])
    return

if __name__ == "__main__":
    xxxxxxxxx()
```
An example traceback from this flow "crashing" is

```

Encountered exception during execution:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1084, in begin_task_run
    return await orchestrate_task_run(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1167, in orchestrate_task_run
    state = await propose_state(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1456, in propose_state
    raise prefect.exceptions.Abort(response.details.reason)
prefect.exceptions.Abort: This run has already terminated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 595, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/colorado_watcher.py", line 54, in colorado_watcher
    send_colorado_slack_update(num_signups, slack_oauth, wait_for=[num_signups])
  File "/usr/local/lib/python3.10/site-packages/prefect/tasks.py", line 295, in __call__
    return enter_task_run_engine(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 735, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 137, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/usr/local/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 863, in get_task_call_return_value
    return await future._result()
  File "/usr/local/lib/python3.10/site-packages/prefect/futures.py", line 236, in _result
    return final_state.result(raise_on_failure=raise_on_failure)
  File "/usr/local/lib/python3.10/site-packages/prefect/orion/schemas/states.py", line 143, in result
    raise data
  File "/usr/local/lib/python3.10/site-packages/prefect/task_runners.py", line 203, in submit
    result = await call()
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1101, in begin_task_run
    task_run.state.data._cache_data(await _retrieve_result(task_run.state))
  File "/usr/local/lib/python3.10/site-packages/prefect/results.py", line 38, in _retrieve_result
    serialized_result = await _retrieve_serialized_result(state.data)
  File "/usr/local/lib/python3.10/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/results.py", line 34, in _retrieve_serialized_result
    return await filesystem.read_path(result.key)
  File "/usr/local/lib/python3.10/site-packages/prefect/filesystems.py", line 183, in read_path
    raise ValueError(f"Path {path} does not exist.")
ValueError: Path /root/.prefect/storage/xxxxxx does not exist.
10:17:24 AM
Crash detected! Execution was interrupted by an unexpected exception.
10:17:24 AM
xxxxxxxx-8e441003-0
Crash details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1084, in begin_task_run
    return await orchestrate_task_run(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1167, in orchestrate_task_run
    state = await propose_state(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1456, in propose_state
    raise prefect.exceptions.Abort(response.details.reason)
prefect.exceptions.Abort: This run has already terminated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 595, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/xxxx.py", line 54, in colorado_watcher
    xxxx(xxxxx, slack_oauth, wait_for=[num_signups])
  File "/usr/local/lib/python3.10/site-packages/prefect/tasks.py", line 295, in __call__
    return enter_task_run_engine(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 735, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 137, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/usr/local/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 863, in get_task_call_return_value
    return await future._result()
  File "/usr/local/lib/python3.10/site-packages/prefect/futures.py", line 236, in _result
    return final_state.result(raise_on_failure=raise_on_failure)
  File "/usr/local/lib/python3.10/site-packages/prefect/orion/schemas/states.py", line 143, in result
    raise data
  File "/usr/local/lib/python3.10/site-packages/prefect/task_runners.py", line 203, in submit
    result = await call()
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1101, in begin_task_run
    task_run.state.data._cache_data(await _retrieve_result(task_run.state))
  File "/usr/local/lib/python3.10/site-packages/prefect/results.py", line 38, in _retrieve_result
    serialized_result = await _retrieve_serialized_result(state.data)
  File "/usr/local/lib/python3.10/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/results.py", line 34, in _retrieve_serialized_result
    return await filesystem.read_path(result.key)
  File "/usr/local/lib/python3.10/site-packages/prefect/filesystems.py", line 183, in read_path
    raise ValueError(f"Path {path} does not exist.")
ValueError: Path /root/.prefect/storage/xxxxx does not exist.
10:17:24 AM
xxxxxx
Crash detected! Execution was interrupted by an unexpected exception.
10:17:24 AM
Crash details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1321, in report_flow_run_crashes
    yield
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 367, in begin_flow_run
    terminal_state = await orchestrate_flow_run(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 654, in orchestrate_flow_run
    state = await propose_state(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1456, in propose_state
    raise prefect.exceptions.Abort(response.details.reason)
prefect.exceptions.Abort: This run has already terminated.

```

**Comment by madkinsz** [comment]
Thanks for sharing that. I believe all of the errors there should be resolved by #6730

**Comment by samgarvis** [comment]
I currently have two flows running every morning on 2.0 because they are very easy to see if they ran or not. I currently have all error notifications turned off. 

That error traceback I sent you was from this morning, both of the flows completed successfully but show crashed.

I believe that branch shows that it is merged, so wouldn't this issue still exist?

Also this the flows crashing mainly only happens when they are scheduled. Pretty much all of the manual runs succeed

**Comment by madkinsz** [comment]
> I believe that branch from https://github.com/PrefectHQ/prefect/pull/6730 shows that it is merged, so wouldn't this issue still exist?

#6730 is merged but not yet released. It should be available tomorrow by EOD — we release on Tuesdays.

**Comment by mikkelduif** [comment]
> If you could provide a MRE that would be very helpful. It's going to be hard for us to solve this issue without a reproducible example.

Sorry for that @madkinsz - though a bit tricky to reproduce it without more info on what is going wrong. Will check 6086, couldn't find it by searching

**Comment by madkinsz** [comment]
👍 I also hard a hard time finding it by searching — not sure what GitHub is up to there.

Are you also seeing `Abort` in your tracebacks?

**Comment by mikkelduif** [comment]
Not as far as I recall - the provided is all the info I have. Have gotten it for quite a while actually - on some occasions it has been due to e.g. OOM or something like that. But we slowly fixed all those issues, and now I really couldn't pinpoint what should actually be the issue anymore.

**Comment by samgarvis** [comment]
> > I believe that branch from #6730 shows that it is merged, so wouldn't this issue still exist?
> 
> #6730 is merged but not yet released. It should be available tomorrow by EOD — we release on Tuesdays.

Got it, thank you

**Comment by madkinsz** [comment]
@samgarvis is this issue resolved for you?

**Comment by samgarvis** [comment]
I'm not sure, I think maybe.
The constant crashing is not happening on as many flows, but it still consistently happens on one of the flows right now. 

Same thing where it actually completes but always shows crashed
I opened #6845 because I am consistently getting a very similar issue.

Sorry I was not able to respond yesterday with more info for #6845, I can try to do that today.

**Comment by vietnguyengit** [comment]
I've got the same error using latest Prefect version: 

![image](https://user-images.githubusercontent.com/26201635/190849569-da58bbaf-e4d4-4388-8648-2797670f0eb8.png)

Flows still reach "Completed" status. but it's annoying!

**Comment by mikkelduif** [comment]
@madkinsz could this be related to re-deploying the flow? I just made an observation that it just happened at the exact same time as our CD was going through. Our approach is always to update all deployment on CD (even if it has not changed). It would also make sense since I guess the file might change path somehow if you redeploy it.

**Comment by john-jam** [comment]
I found one possible reproduction related to the tasks cache.

## Infrastructure
- self-hosted orion API on `k8s`
- self-hosted agent on `k8s`
- Docker image containing the flow code

## Flow (flow.py)
```python
from prefect import task, flow, get_run_logger
from prefect.tasks import task_input_hash

@task(cache_key_fn=task_input_hash)
def cached_task():
    return "cached value"

@flow
def test_cache():
    logger = get_run_logger()

    val = cached_task()
    logger.info(val)

if __name__ == "__main__":
    test_cache()
```

## Test1
If we deploy this flow (deploy to orion API & push docker image) and run it once, it works well. But if we run it again, we hit the error:
```
...
raise ValueError(f"Path {path} does not exist.")
ValueError: Path /root/.prefect/storage/962e40aed4b6451a8f61a34b69e00c9c does not exist.
```

My guess is that prefect tries to fetch from the API the task cache path (the pod receive the PREFECT_API_URL env var) and obviously cannot resolve it locally on a fresh new `k8s` pod.

## Test2
I tried to run the flow in docker locally and I also hit the error if I define the PREFECT_API_URL in the container.

Dockerfile used:
```dockerfile
FROM python:3.8.13-slim-bullseye
RUN pip install prefect==2.4.1
WORKDIR /project
COPY flow.py /project/
ENV PREFECT_API_URL=https://my-public-hostname/api
```

Command used:
```bash
docker build --tag prefect-test-cache . && docker run prefect-test-cache python -m flow
```

If I remove the `ENV` instruction, the flow works well everytime.

**Comment by Manojkl** [comment]
cache_key_fn=task_input_hash, cache_expiration=timedelta(days=1), try to change the cache_expiration to short time period. Or use the update of the cache. 
https://docs.prefect.io/concepts/tasks/#refreshing-the-cache

**Comment by discdiver** [comment]
Agree this appears to be an issue where the cache file can't be checked because it's outside the container. 

Starting with v2.7.8 you can refresh the cache without manually deleting it or setting a short cache_expiration. See more on caching and refreshing the cache [here](https://docs.prefect.io/concepts/tasks/#caching).

It appears the errors in the original issue have been resolved over recent months, so I am going to close with issue, but please reopen if that's not correct.

**Comment by alfa-th** [comment]
On docker as flow container, I found out that if i
1. Reset the cache of the hashed function using `refresh_cache=True`
2. Add `home/user/.prefect/storage:/root/.prefect/storage` to the volume config of my docker container block
![image](https://user-images.githubusercontent.com/35270908/221252232-dbe238cb-22d5-480e-9456-e75fc827fbdb.png)

A function with `cache_key_fn=task_input_hash` worked perfectly. Maybe someone else try it idk
