### ISSUE TITLE
Copy to New Run Request in UI shows inconsistent parameters

### ISSUE THREAD

**Issue by jbnitorum** [PrefectHQ/prefect#9534]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

In the UI when you select the three dots in the top right you have the option "Copy to new run".  When you do that presumably you are presented with a form to create a new flow run for the same deployment and presumably with the same parameters.  The run form that is presented defaults to having the toggle for parameters set to 'Custom'  and the parameters are each set to their default values as defined in the flow code and NOT the parameters from the run.  I assume this IS NOT the expected behavior.  If you change the toggle to JSON you WILL see the parameters from the run being copied.  I assume this IS the expected behavior.

### Reproduction

Create a flow with a parameter that has a default value defined in the flow code.  Run that flow with a value for parameter other than the default value.  Go to the page for that flow run.  Click 'Copy to new run'.  Resulting page will show toggle in Parameter section set to 'Custom' and your parameter will be filled with the default value found in your flow code and NOT the value you ran the flow you copied this from.  if you change the toggle to JSON you will see the other value that you copied from the other flow run.

### Versions

```Text
Cloud
```

**Comment by jbnitorum** [comment]
Sorry... just realized I used the wrong form to submit this since its a UI bug

**Comment by madkinsz** [comment]
@jbnitorum no problem can you edit your issue so it's a bit more readable?

**Comment by jbnitorum** [comment]
@madkinsz done

**Comment by j-tr** [comment]
@jbnitorum @madkinsz we are also experiencing this in Prefect Cloud. there is additional unexpected behavior when using pydantic models.
This example shows that for a bit more complex parameter models, data from the default and previous run is mixed.

```
from prefect import flow
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

class Param(BaseModel):
    some_complex_object: Optional[List[Dict[str, Any]]] = Field(
                title="some_complex_object",
                default=None,
            )

@flow(
    name="PydanticModelUITest",
    log_prints=True
)
def main(
    config: Param = Param(
        some_complex_object=[
            {
                "foo": "foo1",
                "bar": "bar1",
                "foo_bar": "foo_bar1"
            },
            {
                "foo": "foo2",
                "bar": "bar2",
                "foo_bar": "foo_bar2"
            }
        ]
    )
) -> None:
    print(config)


if __name__ == "__main__":
    main()
```

This presents in the UI like this:
![image](https://github.com/PrefectHQ/prefect/assets/11021147/13fba269-3fd7-4801-b17e-fe6c50bce343)

when i change the parameter like below and submit a run, this creates a flow run with the expected parameters (the ones i specified and not the default parameters)
![image](https://github.com/PrefectHQ/prefect/assets/11021147/58f466e5-d028-48a1-aa45-0b1c28bb10b1)
![image](https://github.com/PrefectHQ/prefect/assets/11021147/750c3273-f98b-4bc5-90b6-5bd476d9df4f)

when i use "Copy to new run" on the last run with modified input, this presents the input field with merged data from both, the dafault values and the values from the last run, which i would not expect.
![image](https://github.com/PrefectHQ/prefect/assets/11021147/2a27ede2-5bfc-4c75-8fec-71790320b2e0)

if i now submit this run without touching the input field it runs with the parameters from the previous run and not the parameters that were displayed in the UI, which i would also consider unexpected behaviour
![image](https://github.com/PrefectHQ/prefect/assets/11021147/750c3273-f98b-4bc5-90b6-5bd476d9df4f)

however, if i do touch the input field and change something, the flow runs with the parameters from the input field
![image](https://github.com/PrefectHQ/prefect/assets/11021147/db7ea9f9-4754-4b8c-9cea-01b8837772de)
![image](https://github.com/PrefectHQ/prefect/assets/11021147/a20c6d40-2d14-498b-b6d9-164c3d35626e)

In this case, it might be obvious to the user that two list elements are displayed here whereas there was only one in the previous flow, however with more complex configs, this is very hard to spot.

This is extremely concerning and caused a lot of issues down the road for us.
We have flows with quite large configurations and flows are often executed by "Copy to new run", changing a small detail in the config and running it again.
With this bug, we need to carefully check each configuration before running because we cannot rely on the fact that it is the same as for the last flow run but actually a mix of different parameter sets that will be used as soon as we edit a detail. Submitting flows with such a wrong configuration can have a very serious impact on our production workflows.
In one of more complex examples, not only elements of the list were added but values from the inner dictionaries were swapped between elements of the list.

**Comment by zhen0** [comment]
Should be fixed by https://github.com/PrefectHQ/prefect-ui-library/pull/1412

**Comment by zhen0** [comment]
> ~Thank you for raising - this should be fixed by [PrefectHQ/prefect-ui-library#1412](https://github.com/PrefectHQ/prefect-ui-library/pull/1412)~
> 
> Actually reading through the detail above, I want to run a bit of extra QA to be certain it fixes the wider issues.

Yep - using the examples provided above this should be resolved by https://github.com/PrefectHQ/prefect-ui-library/pull/1412

**Comment by batuhanfaik** [comment]
Thank you for bringing this up! I thought I was hallucinating/misremembering 😂

**Comment by EmilRex** [comment]
Closing this as https://github.com/PrefectHQ/prefect-ui-library/pull/1412 has been merged. @zhen0 please reopen if I misunderstood.

**Comment by mscanlon-exos** [comment]
@EmilRex Can we reopen this? Still seeing this behavior for datetime parameters

**Comment by mscanlon-exos** [comment]
> @EmilRex Can we reopen this? Still seeing this behavior for datetime parameters

can also make a new issue request if neccesary and tag this

**Comment by EmilRex** [comment]
@mscanlon-exos of course! Just to confirm, you're seeing this in Prefect Cloud, correct?

**Comment by EmilRex** [comment]
@jbnitorum was this resolved for you?

**Comment by jbnitorum** [comment]
@EmilRex I saw it resolved but I didn't test it extensively.  I can't speak to datetime params specifically.

**Comment by mscanlon-exos** [comment]
> @mscanlon-exos - any chance you can provide an MRE or an example here so we can look into it?

@zhen0 I believe it would be the same workflow as this issue, just ensure you have a datetime param. 
In the custom tab, you should see `mm/dd/yyyy` but in the json tab, youll see the previously populated date as a string. Happy to share an example over email if necessary. Just don't want to post sensitive data here!

**Comment by zhen0** [comment]
> > @mscanlon-exos - any chance you can provide an MRE or an example here so we can look into it?
> 
> 
> 
> @zhen0 I believe it would be the same workflow as this issue, just ensure you have a datetime param. 
> 
> In the custom tab, you should see `mm/dd/yyyy` but in the json tab, youll see the previously populated date as a string. Happy to share an example screen recording over email if necessary. Just don't want to post sensitive data here! FYI this is prefect cloud. Idk if the non-enterprise version has a slightly different ui

Great thank you. Let's try what you said and then we can come back for more info if needed.

**Comment by pleek91** [comment]
A fix for this has be deployed to cloud and will also be included in todays open source release. I'll leave this issue open for now but neither myself nor @zhen0 can reproduce this after the fix was applied.

**Comment by mscanlon-exos** [comment]
> A fix for this has be deployed to cloud and will also be included in todays open source release. I'll leave this issue open for now but neither myself nor @zhen0 can reproduce this after the fix was applied.

Amazing! Thank you !!!
